rootUrl: 'http://localhost:8888'
# screenshotsDir: './screens'
# windowSize: 600x400
compositeImage: true             # fix "The region bottom bound is outside of the viewport height"
screenshotMode: 'fullpage'
sessionsPerBrowser: 3

system:
  # exclude:
  #   - 'gemini/gemini-reports/**'
  #   - 'node_modules/**'
  plugins:
    browserstack: {}
    'html-reporter':
      enabled: true
      path: 'gemini/gemini-reports'
      errorsOnly: false
      baseHost: 'http://localhost:8888'
 
browsers:
  ie:
    windowSize: 600x10000
    desiredCapabilities:
      os: 'WINDOWS'
      os_version: '7'
      browserName: 'internet explorer'
      version: '8'
 
  chromeSmall:
    windowSize: 400x1024
    desiredCapabilities:
      os: 'WINDOWS'
      os_version: '7'
      browserName: 'chrome'
      version: '18'

  chromeMedium:
    windowSize: 768x1024
    desiredCapabilities:
      os: 'WINDOWS'
      os_version: '7'
      browserName: 'chrome'
      version: '18'

  chromeLarge:
    windowSize: 1024x768
    desiredCapabilities:
      os: 'WINDOWS'
      os_version: '7'
      browserName: 'chrome'
      version: '18'

  firefox:
    windowSize: 1024x768
    desiredCapabilities:
      os: 'WINDOWS'
      os_version: '7'
      browserName: 'firefox'
      version: '4'

sets:
  desktop:
    files:
      - 'gemini/tests/desktop'
    browsers:
      - ie
      - chromeSmall
      - chromeMedium
      - chromeLarge
      - firefox